package Main

/**
 * Created on 30/10/2019
 * Time 13:08H
 *
 * @author Stefano Mazzuka
 */
object GUI {

  def cls(): Unit = {
    val os: String = System.getProperty("os.name")
    if (os.contains("Windows")) {
      new ProcessBuilder("cmd", "/c", "cls").inheritIO.start.waitFor
    }
    else {
      Runtime.getRuntime.exec("clear")
    }
  }
  def title(): Unit = {
    println("╔════════════════════════════════════════════════════════════════════╗")
    println("║                  ___           _                                   ║")
    println("║                   | |_   _    /   _.  _ _|_ |  _                   ║")
    println("║                   | | | (/_   \\_ (_| _>  |_ | (/_                  ║")
    println("║                                                                    ║")
    println("╚════════════════════════════════════════════════════════════════════╝")
  }
  def castle(): Unit = {
    println("                                  |>>>")
    println("                                  |")
    println("                    |>>>      _  _|_  _         |>>>")
    println("                    |        |;| |;| |;|        |")
    println("                _  _|_  _    \\\\.    .  /    _  _|_  _")
    println("               |;|_|;|_|;|    \\\\:. ,  /    |;|_|;|_|;|")
    println("               \\\\..      /    ||;   . |    \\\\.    .  /")
    println("                \\\\.  ,  /     ||:  .  |     \\\\:  .  /")
    println("                 ||:   |_   _ ||_ . _ | _   _||:   |")
    println("                 ||:  .|||_|;|_|;|_|;|_|;|_|;||:.  |")
    println("                 ||:   ||.    .     .      . ||:  .|")
    println("                 ||: . || .     . .   .  ,   ||:   |       \\,/")
    println("                 ||:   ||:  ,  _______   .   ||: , |            /`\\")
    println("                 ||:   || .   /+++++++\\    . ||:   |")
    println("                 ||:   ||.    |+++++++| .    ||: . |")
    println("              __ ||: . ||: ,  |+++++++|.  . _||_   |")
    println("     ____--`~    '--~~__|.    |+++++__|----~    ~`---,              ___")
    println("-~--~                   ~---__|,--~'                  ~~----_____-~'   `~--")
  }
  def showMessage(message: String): Unit = {
    GUI.cls()
    print("╔")
    for (i <- 0 to message.size + 1)
      print("═")
    println("╗")
    println("║ " + message + " ║")
    print("╚")
    for (i <- 0 to message.size + 1)
      print("═")
    println("╝")
    knigth()
    println("press any key to continue...")
    val op = scala.io.StdIn.readLine()
  }
  def knigth(): Unit = {
    println("                   _.--.    .--._")
    println("                 .\"  .\"      \".  \".")
    println("                ;  .\"    /\\    \".  ;")
    println("                ;  '._,-/  \\-,_.`  ;")
    println("                \\  ,`  / /\\ \\  `,  /")
    println("                 \\/    \\/  \\/    \\/")
    println("                 ,=_    \\/\\/    _=,")
    println("                 |  \"_   \\/   _\"  |")
    println("                 |_   '\"-..-\"'   _|")
    println("                 | \"-.        .-\" |")
    println("                 |    \"\\    /\"    |")
    println("                 |      |  |      |")
    println("         ___     |      |  |      |     ___")
    println("     _,-\",  \",   '_     |  |     _'   ,\"  ,\"-,_")
    println("   _(  \\  \\   \\\"=--\"-.  |  |  .-\"--=\"/   /  /  )_")
    println(" ,\"  \\  \\  \\   \\      \"-'--'-\"      /   /  /  /  \".")
    println("!     \\  \\  \\   \\                  /   /  /  /     !")
    println(":      \\  \\  \\   \\                /   /  /  /      :")
  }
  def choosePlayer(): Unit = {
    println("╔════════════════════════════════════╗")
    println("║           Who's there!?            ║")
    println("╠════════════════════════════════════╣")
    println("║ 1. I'm your King! Open the gate!   ║")
    println("║ 2. The best knight in the kingdom! ║")
    println("║ 3. The Holy Bishop                 ║")
    println("║ 4. Just another Guard              ║")
    println("║ 5. Hi, i'm a... Peasent            ║")
    println("║ 6. Sorry! Wrong castle             ║")
    println("╚════════════════════════════════════╝")
    print("Select option: ")
  }
  def outside(): Unit = {
    println("        --1--        ")
    println("         | |         ")
    println("         | |         ")
    println("         | |         ")
    println("         |  ======[2]")
    println("         | |         ")
    println("         | |         ")
    println("         | |         ")
    println("         | |         ")
    println("         | |         ")
    println("        --3--        ")
    println()
    println("╔══════════════════════╗")
    println("║        Outside       ║")
    println("╠══════════════════════╣")
    println("║ 1. To Living room    ║")
    println("║ 2. To Secret Passage ║")
    println("║ 3. Outside the gate  ║")
    println("╚══════════════════════╝")
    print("Select option: ")
  }
  def livingRoom(): Unit = {
    println("        --2--        ")
    println("                    |")
    println("       _______      3")
    println("      | ----- |     |")
    println("|     ||     ||      ")
    println("1     ||     ||      ")
    println("|     ||     ||     -")
    println("      ||_____||    - ")
    println("       -------    4  ")
    println("                 -   ")
    println("        --5--   -    ")
    println()
    println("╔══════════════════════════╗")
    println("║        Living Room       ║")
    println("╠══════════════════════════╣")
    println("║ 1. To Dining Room        ║")
    println("║ 2. To Armoury            ║")
    println("║ 3. To Kitchen            ║")
    println("║ 4. To Second floor       ║")
    println("║ 5. To Outside the Castle ║")
    println("╚══════════════════════════╝")
    print("Select option: ")
  }
  def diningRoom(): Unit = {
    println("                     ")
    println("                     ")
    println("        _____        ")
    println("       |     |       ")
    println("       |     |      |")
    println("       |     |      1")
    println("       |     |      |")
    println("       |_____|       ")
    println("        |   |        ")
    println("                     ")
    println("                     ")
    println()
    println("╔═══════════════════╗")
    println("║    Dining Room    ║")
    println("╠═══════════════════╣")
    println("║ 1. To Living Room ║")
    println("╚═══════════════════╝")
    print("Select option: ")
  }
  def armoury(): Unit = {
    println("                     ")
    println("     |`-._/\\_.-`|   ")
    println("     |    ||    |    ")
    println("     |___o()o___|    ")
    println("     |__((<>))__|    ")
    println("     \\   o\\/o   /  ")
    println("      \\   ||   /    ")
    println("       \\  ||  /     ")
    println("        '.||.'       ")
    println("          ``         ")
    println("        --1--        ")
    println()
    println("╔═══════════════════╗")
    println("║      Armoury      ║")
    println("╠═══════════════════╣")
    println("║ 1. To Living Room ║")
    println("╚═══════════════════╝")
    print("Select option: ")
  }
  def kitchen(): Unit = {
    println("                     ")
    println("|                    ")
    println("3                    ")
    println("|                    ")
    println("            \\\\\\   ")
    println("     ________```     ")
    println("    [________] \\    ")
    println("    |        |  \\   ")
    println("    `.______.'   \\  ")
    println("                     ")
    println("                     ")
    println()
    println("╔═══════════════════╗")
    println("║      Kitchen      ║")
    println("╠═══════════════════╣")
    println("║ 1. To Living Room ║")
    println("╚═══════════════════╝")
    print("Select option: ")
  }
  def secondFloor(): Unit = {
    println("        --2--        ")
    println("                     ")
    println("       _______       ")
    println("      | ----- |      ")
    println("|     ||     ||     |")
    println("1     ||     ||     3")
    println("|     ||     || -   |")
    println("      ||_____||  -   ")
    println("       -------    4  ")
    println("                   - ")
    println("                    -")
    println()
    println("╔═══════════════════╗")
    println("║ Second floor hall ║")
    println("╠═══════════════════╣")
    println("║ 1. To Bathroom    ║")
    println("║ 2. To Chapel      ║")
    println("║ 3. To Kings Room  ║")
    println("║ 4. To First floor ║")
    println("╚═══════════════════╝")
    print("Select option: ")
  }
  def bathroom(): Unit = {
    println("                     ")
    println("                     ")
    println("      .__   .-\".    ")
    println("     (o\\\"\\  |  |  ")
    println("        \\_\\ |  |    |")
    println("       _.---:_ |    1")
    println("      (\"-..-\" /     |")
    println("       \"-.-\" /     ")
    println("         /   |       ")
    println("         \"--\"      ")
    println("                     ")
    println()
    println("╔═════════════════════════╗")
    println("║        Bathroom         ║")
    println("╠═════════════════════════╣")
    println("║ 1. To Second floor hall ║")
    println("╚═════════════════════════╝")
    print("Select option: ")
  }
  def chapel(): Unit = {
    println("         .-.         ")
    println("         | |         ")
    println("     ____|!|____     ")
    println("    |____-+-____|    ")
    println("         |!|         ")
    println("         | |         ")
    println("         | |         ")
    println("         | |         ")
    println("       __|_|__       ")
    println("      /_______\\     ")
    println("        --1--        ")
    println()
    println("╔═════════════════════════╗")
    println("║         Chapel          ║")
    println("╠═════════════════════════╣")
    println("║ 1. To Second floor hall ║")
    println("╚═════════════════════════╝")
    print("Select option: ")
  }
  def kingsRoom(): Unit = {
    println("          o            ")
    println("          |         [2]")
    println("    o    ,|.           ")
    println("    |  ,' \\ `.        ")
    println("|   |,'\\,' ,' `.   o  ")
    println("1   |.`. ,'     `. |   ")
    println("|   | `.`.    o  ,'|   ")
    println("        `.`.  |,'  |   ")
    println("          `.`.|  ,'|   ")
    println("            `.|,'      ")
    println("              |        ")
    println()
    println("╔═════════════════════════╗")
    println("║        Kings Room       ║")
    println("╠═════════════════════════╣")
    println("║ 1. To Second floor hall ║")
    println("║ 2. To Secret Passage    ║")
    println("╚═════════════════════════╝")
    print("Select option: ")
  }
}
